import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { isSpecificationProvider } from "../src/providers/specification";
import { FALLBACK_PROVIDER_NAME, createFallbackProvider } from "../src/providers/fallback";

// Fallback provider tests: no external dependencies.
describe("fallback specification provider", () => {
  it("satisfies the generic contract with the fallback identity", () => {
    assert.equal(FALLBACK_PROVIDER_NAME, "fallback");
    const provider = createFallbackProvider();
    assert.equal(isSpecificationProvider(provider), true);
    assert.equal(provider.name, "fallback");
  });

  it("produces a specification artifact with requirements preserved", async () => {
    const provider = createFallbackProvider();
    const result = await provider.generate({
      requirements: 'Build a "quoted" $shop.',
      project_root: "/proj",
      artifact: "specification",
    });
    assert.equal(result.artifact, "specification");
    assert.ok(result.content.includes("Generated by the framework fallback provider"));
    assert.ok(result.content.includes("## Requirements (preserved verbatim from PM input)"));
    assert.ok(result.content.includes('Build a "quoted" $shop.'));
  });

  it("produces a plan artifact with requirements preserved", async () => {
    const provider = createFallbackProvider();
    const result = await provider.generate({
      requirements: "Build a shop.",
      project_root: "/proj",
      artifact: "plan",
    });
    assert.equal(result.artifact, "plan");
    assert.ok(result.content.includes("# Plan"));
    assert.ok(result.content.includes("Build a shop."));
  });

  it("rejects invalid requests before generating output", async () => {
    const provider = createFallbackProvider();
    await assert.rejects(
      provider.generate({ requirements: "", project_root: "/proj", artifact: "plan" }),
      /invalid input/,
    );
    await assert.rejects(
      provider.generate({ requirements: "Build.", project_root: "/proj", artifact: "tasks" as unknown as "plan" }),
      /invalid input/,
    );
  });

  it("produces deterministic output for identical requests", async () => {
    const provider = createFallbackProvider();
    const first = await provider.generate({ requirements: "Build.", project_root: "/proj", artifact: "plan" });
    const second = await provider.generate({ requirements: "Build.", project_root: "/proj", artifact: "plan" });
    assert.deepEqual(first, second);
  });

  it("returns immutable artifacts that pass the shared validator", async () => {
    const provider = createFallbackProvider();
    const result = await provider.generate({ requirements: "Build.", project_root: "/proj", artifact: "specification" });
    assert.equal(Object.isFrozen(result), true);
    // Re-validate via the shared contract.
    const module = await import("../src/providers/specification");
    const revalidated = module.validateSpecificationArtifact(result);
    assert.deepEqual(revalidated, result);
  });

  it("leaks no transport, provider metadata, or provenance into the artifact", async () => {
    const provider = createFallbackProvider();
    const result = await provider.generate({ requirements: "Build.", project_root: "/proj", artifact: "plan" });
    assert.deepEqual(Object.keys(result).sort(), ["artifact", "content"]);
    assert.ok(!result.content.includes("opencode"));
    assert.ok(!result.content.includes("spec-kit"));
  });

  it("keeps the public API minimal", async () => {
    const module = await import("../src/providers/fallback");
    assert.deepEqual(Object.keys(module).sort(), ["FALLBACK_PROVIDER_NAME", "createFallbackProvider"]);
  });

  it("adds no Spec Kit, agent execution, installation, or routing", async () => {
    const fs = await import("node:fs/promises");
    const code = await fs.readFile(join(__dirname, "..", "..", "src", "providers", "fallback.ts"), "utf8");
    assert.ok(!/speckit|specify|opencode|AgentProvider|opencode/i.test(code), "no Spec Kit coupling");
    assert.ok(!/child_process|execSync|spawn|fetch\(|http|node:/i.test(code), "no execution");
    assert.ok(!/\b(install|uvx|bootstrap|detect)\b/i.test(code), "no setup behavior");
    assert.ok(!/github|issue|regist|cli|workflow|config/i.test(code), "no surrounding integration");
  });
});