/**
 * Fallback specification provider (P-005).
 *
 * A self-contained `SpecificationProvider` that operates without
 * Spec Kit. Given PM-owned requirements, it produces a minimal
 * deterministic artifact for either kind. No external tools, no
 * detection, no installation, no Spec Kit coupling. The generated
 * artifact is designed to be consumable by P-003/P-004 without
 * claiming Spec Kit equivalence.
 */

import { SpecificationArtifact, SpecificationProvider, SpecificationRequest, validateSpecificationArtifact, validateSpecificationRequest } from "./specification";

/** Stable fallback identity, local to this concrete module. */
export const FALLBACK_PROVIDER_NAME = "fallback" as const;

function buildSpecificationArtifact(request: SpecificationRequest): SpecificationArtifact {
  const header = request.artifact === "plan" ? "Plan" : "Specification";
  const content = [
    `# ${header}`,
    "",
    "Generated by the framework fallback provider (Spec Kit unavailable).",
    "",
    "## Requirements (preserved verbatim from PM input)",
    "",
    request.requirements,
  ].join("\n");
  return validateSpecificationArtifact({ artifact: request.artifact, content });
}

/**
 * Build the fallback provider. No external dependencies; artifact
 * generation is synchronous and purely structural.
 */
export function createFallbackProvider(): SpecificationProvider {
  return {
    name: FALLBACK_PROVIDER_NAME,
    generate: async (request: SpecificationRequest): Promise<SpecificationArtifact> => {
      const invocation = validateSpecificationRequest(request);
      return buildSpecificationArtifact(invocation);
    },
  };
}